version: '3.8'

services:
  # app:
  #   build: .
  #   container_name: "api-server"
  #   command: sh -c "npm run knex:migrate && npm run build && npm run start:dev"
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - .:/usr/app
  #   links:
  #     - db
  #   depends_on:
  #     - db
  #   environment: 
  #     DB_HOST: host.doker.internal
  #     DB_USER: postgres
  #     DB_PASS: 1234@mudar
  db:
    image: postgres:alpine
    container_name: api-db
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_PASSWORD=1234@mudar